[project]
name = "marginaleffects-r"
version = "0.1.0"
description = "Python dependencies for marginaleffects R package"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "pip",
  "marginaleffects>=0.3.0",
  "jax>=0.8.0",
  "numpy"
]

